version: "3.9"
services:
  app:
    image: "${IMAGE_TAG}"
    environment:
      - NODE_ENV
      - PORT
    ports:
      - "${PORT}:${PORT}"
  automation:
    build: ./app/test/automation
    depends_on:
      - app
    environment:
      - CYPRESS_BASE_URL
