version: "3.9"
services:
  web:
    command: /bin/bash -c "npm run dev:build; npm run dev:build:watch & npm run dev:start;"
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - .:/home/node/app