version: "3.9"
services:
  app:
    image: app:local
    environment:
      - NODE_ENV
      - PORT=3000
    ports:
      - "3000:3000"
  automation:
    build: ./app/test/automation
    depends_on:
      - app
    environment:
      - CYPRESS_BASE_URL=http://app:3000
