version: "3.9"
services:
  app:
    image: "${IMAGE_TAG}"
    environment:
      - NODE_ENV
      - SERVER_PORT
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
  automation:
    build: ./app/test/automation
    depends_on:
      - app
    environment:
      - CYPRESS_BASE_URL=http://app:${SERVER_PORT}